name: hmm_env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.0=py37hc8dfbb8_1001
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.4=pyh9f0ad1d_0
  - brotlipy=0.7.0=py37h0b31af3_1000
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cffi=1.14.0=py37h356ff06_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - cryptography=2.8=py37he655712_2
  - cycler=0.10.0=py37_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - freetype=2.9.1=hb4e5f40_0
  - idna=2.9=py_1
  - importlib-metadata=1.6.0=py37hc8dfbb8_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2019.4=233
  - ipykernel=5.2.0=py37h43977f1_1
  - ipython=7.13.0=py37hc8dfbb8_2
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.0=py37hc8dfbb8_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.14.1=py_0
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyterlab=2.1.0=py_0
  - jupyterlab_server=1.1.1=py_0
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.17=h01d97ff_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - markupsafe=1.1.1=py37h9bfed18_1
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h9aa3819_0
  - mistune=0.8.4=py37h9bfed18_1001
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.4=py_0
  - ncurses=6.2=h0a44026_0
  - notebook=6.0.3=py37_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h6575580_1
  - openssl=1.1.1f=h0b31af3_0
  - pandas=1.0.3=py37h6c726b0_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pip=20.0.2=py37_1
  - prettytable=0.7.2=py_3
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.6=py_0
  - pyrsistent=0.16.0=py37h9bfed18_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.7=hc70fcce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pyzmq=18.1.1=py37h0a44026_0
  - readline=8.0=h1de35cc_0
  - requests=2.23.0=pyh8c360ce_2
  - scikit-learn=0.22.1=py37h27c97d8_0
  - scipy=1.4.1=py37h9fa6033_0
  - seaborn=0.10.0=py_0
  - send2trash=1.5.0=py_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py37h1de35cc_1
  - traitlets=4.3.3=py37hc8dfbb8_1
  - urllib3=1.25.9=py_0
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/esukei/anaconda3/envs/hmm_env

